### PR TITLE
Pass number format setting to prevent accuracy lost

### PR DESCRIPTION
**Pull request by chiu0602**

### CODE REVIEW

**Comment by anandanand84** [comment]
Hi chiu

Thanks for your pull request. I checked your fork it looks good, except the test are failing. You can run the test by running "mocha" in the root folder.

1. Those are minor fixes where you need to edit the test data from 0.59 to 0.58. 

2. Also there are places like KST where rounding is not working since the rounding has to be done for ROC as well. 

3. If you can also add the test case in the issue https://github.com/anandanand84/technicalindicators/issues/1 and make it pass it will be helpful so we can close that issue.

Thanks again your work.

**Comment by anandanand84** [comment]
Actually I tried the test in issue 1 and it works you can add it in test/moving_averages/SMA.js

```
it('should be able to get SMA for low values(issue 1)', function() {
    let expectedResult = [ 0.002, 0.00275, 0.0025, 0.003, 0.003, 0.0025 ];
    assert.deepEqual(SMA.calculate({period : 4, values : [0.001, 0.003, 0.001, 0.003, 0.004, 0.002, 0.003, 0.003, 0.002]}), expectedResult, 'Wrong Results');
  })
```

**Comment by anandanand84** [comment]
Thank you. I'll verify and merge soon

**Comment by chiu0602** [comment]
by the way, @anandanand84 thanks for your great work!

**Pull request merged**
