### PR TITLE
Fixes RSI returns on consistent moves

### PR DESCRIPTION
**Pull request by Tetradeca**
I've generated the js files, but refrained from creating the dist bundle in this diff.

Would you consider pushing the `lib` and `dist` folders only to npm and not to Github? It's quite a hassle to maintain and kinda pollutes the repo. You are also subject to vulnerabilities in case a malicious user decides to include evil col in the minified bundles, and you forget to regenerate it before publishing (which appears to be the case since I have a few other lib files uncommitted).

I could create a PR in that purpose if you'd like.

### CODE REVIEW

**Comment by anandanand84** [comment]
Thanks for taking the time to contribute to this repository.

sure, I agree with you  and I had that in my plan to generate lib and dist directory with npm publish lifecycle scripts, but for ignoring from github makes it unusable for people who use rawgit cdn.  May be, we can generate lib and dist in prepublish and push generated lib and dist in postpublish scripts which will solve your concerns of maintanence hassle. What do you think?

If you can add these change as well in this pull request I would merge them both together. 

Thanks

**Comment by Tetradeca** [comment]
Might be a better idea to separate concerns, I don't mind making another PR ;)

Is there a lot of people using RawGit? Because we could orient them into using https://unpkg.com instead. Which would have the benefits of both CDN support and a pretty neat repo

**Comment by anandanand84** [comment]
ok, Lets remove the lib and dist and add it in Readme to use unpkg.com if using rawgit.

**Comment by Tetradeca** [comment]
Neat! Will you merge this PR or do you _really_ want me to do both changes in this one? 😃

**Comment by anandanand84** [comment]
no I will merge this

**Comment by anandanand84** [comment]
@Tetradeca I created a test and it did not pass 

```
var noGainsInput = {
 values : [ 294435, 294435, 294435, 294500, 294500, 294500, 294520, 294539, 294539, 294600, 294600, 294600, 294600, 294600, 294700 ],
 period : 14
};
var noGainsExpectedResult = [
 100,70.53,66.32,66.55,69.41,66.36,57.97,62.93,63.26,56.06,62.38
];

it('should calculate RSI when there is no gains or losses', function () {
  let result = RSI.calculate(noGainsInput);
  assert.deepEqual(result, noGainsExpectedResult, 'Wrong Results');
});
```

image

**Pull request merged**
