### PR TITLE
Add CrossUp, CrossDown and CrossOver indicator

### PR DESCRIPTION
**Pull request by cwouter**
This indicator returns true or false if one line crosses another line. In case the previous value of line A equals to line B the indicator will look back until it can find a (in)valid cross and returns true/false accordingly.

Later on i'll add cross down and full cross indicator.

### CODE REVIEW

**Comment by anandanand84** [comment]
Thankyou I'll try to get this merged tonight

**Comment by cwouter** [comment]
Thx for the quick response. Should I add CrossDown and CrossOver in a separate PR? I can add both indicators tonight.

**Comment by anandanand84** [comment]
you can add it in the same

**Comment by cwouter** [comment]
I've added the CrossDown and CrossOver indicators. Is the build script still up-to-date? Because on my computer it outputs: 

```
dts-bundle version 0.7.3
Export TypeScript .d.ts files as an external module definition

sed: 1: "declarations/generated. ...": extra characters at the end of d command
sed: 1: "declarations/generated. ...": extra characters at the end of d command
```

**Comment by cwouter** [comment]
@anandanand84 , would you be able to merge this in the next few days? Or can I help you to speed up the merging process? thx

**Comment by anandanand84** [comment]
did you change anything in the tests, I am not able to run all the tests, only crossover tests are being run?

**Comment by anandanand84** [comment]
> I've added the CrossDown and CrossOver indicators. Is the build script still up-to-date? Because on my computer it outputs:
> 
> ```
> dts-bundle version 0.7.3
> Export TypeScript .d.ts files as an external module definition
> 
> sed: 1: "declarations/generated. ...": extra characters at the end of d command
> sed: 1: "declarations/generated. ...": extra characters at the end of d command
> ```

This works only in linux, did you try in mac?

**Comment by anandanand84** [comment]
v3.1.0 published with changes

**Pull request merged**
