### PR TITLE
Rename renko.js to Renko.js

### PR DESCRIPTION
**Pull request by balupton**
Fixes the readme link to https://github.com/anandanand84/technicalindicators/blob/master/test/chart_types/Renko.js

Alternative approach was to update the readme link to https://github.com/anandanand84/technicalindicators/blob/master/test/chart_types/renko.js however the naming convention seems to imply that it should be `Renko.js` instead of `renko.js`

### CODE REVIEW

**Comment by anandanand84** [comment]
@balupton  Did you get a chance to test it? I dont have any test case for this, as I didn't find anything online. The only way I can check is get data from trading view by hovering over the bars which is too time consuming. any thoughts?

**Comment by balupton** [comment]
Will see about testing it. I'll be doing much the same. I've only found about 5 implementations of renko on GitHub in various languages, and not sure if any include tests.

My plan is accumulate a fair bit of tick data, publish it as a package, and then do fixtures up for what Trading View provides for the different time spans.

**Comment by anandanand84** [comment]
I havent used renko before. Maybe I'll implement in my charting package https://traderslab.in/ and you can tell if it is correct by looking visually comparing with trading view

**Comment by anandanand84** [comment]
@balupton I have fixed few issues in renko and tried in actual chart, attached the screenshot, I am not familiar with renko, can you verify if it looks correct.

screen shot 2017-07-28 at 3 28 14 pm

**Comment by balupton** [comment]
Will verify over the coming week. Thank you for your efforts on this.

**Pull request merged**
